### ISSUE TITLE
[DataCap Application] <Rivtower> - <Rivtower Techonology>

### ISSUE THREAD

**Issue by Rivtower-work** [ipfsAllen/Fil-DC-Allocator-Allen#11]
### Data Owner Name

Rivtower

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://www.rivtower.com/

### Social Media Handle

Rivtower

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

650TiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1mdpz7567ckomsffupv2snj5evhqn2oqslrave6i

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Rivtower Technology was established in 2019 and is headquartered in Hangzhou. There are wholly-owned subsidiaries in Beijing, Shanghai and Suzhou. Our company is mainly engaged in the research and development of blockchain basic technology, blockchain application tools, and blockchain management platforms. Our projects cover the core parts in the blockchain field. For example, we designed and developed the enterprise-level and high-performance blockchain core CITA open source project, and established CITAHub, an open source technology exchange community, helps combine technology and business. The 2020 World Internet Conference released China's first cloud-native blockchain framework CITA-Cloud. What's more, the 2021 World Internet Conference released the RivSpace enterprise-level blockchain management platform and the RivTrust data asset management platform.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
There are documents, videos, photos, etc. For example, the company's platform users generate data involving supply chain, finance, leasing, government affairs, and energy.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Firstly our data is mainly stored on our hardware servers, so we mainly transfer the data through network bandwidth. We mainly use compression tools to compress the data for transmission.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No. There are documents, videos, photos, etc. For example, the company's platform users generate data involving supply chain, finance, leasing, government affairs, and energy.
```

### Please share a sample of the data

```text
http://mpvideo.qpic.cn/0b2ezyaauaaaauao3kgdpvqvbtwdblhaacqa.f10003.mp4?dis_k=36d7d6c5b9839ac581fb689f61cd7766&dis_t=1652931215
http://mpvideo.qpic.cn/0b2ekiaauaaaiqao3sodrzqvauwdbjjaacqa.f10003.mp4?dis_k=8a03316309e7e3173059986b72bce8dd&dis_t=1652931234
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
Because most of this data is generated in the operation of the enterprise, it belongs to the private data
```

### What is the expected retrieval frequency for this data

Never

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02224274 - hk
f02826234 - Singaporean
f01926635 - sichuan
f02948413 - china
f03091958 - South Korea
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by ipfsAllen** [comment]
checker:manualTrigger works well. [#6 datacap-bot](https://github.com/ipfsAllen/Fil-DC-Allocator-Allen/issues/6#issuecomment-2187704312)
I don't think there's a system bug, so I'm closing this application.
